import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mail, Phone, MapPin, Send, MessageSquare, ChevronDown } from 'lucide-react';
import { toast } from 'react-toastify';
import axios from 'axios';

const Contact = () => {
  const [formData, setFormData] = useState({ name: '', email: '', subject: '', message: '' });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [openFaqIndex, setOpenFaqIndex] = useState(null);

  const faqs = [
    { question: 'Is ai-coach completely free to use?', answer: 'Yes! The core platform features including resume analysis, basic AI interviews, and portfolio generation are completely free during our beta phase.' },
    { question: 'How secure is my resume data?', answer: 'We take privacy seriously. Your resumes are securely stored and never shared with third parties. You can delete your data at any time from your account settings.' },
    { question: 'Can I use the portfolio generator for commercial projects?', answer: 'Absolutely. The code generated by our Portfolio Builder is 100% yours. You can deploy it anywhere and modify it as you see fit.' },
    { question: 'How accurate is the Resume ATS Scanner?', answer: 'Our scanner uses logic matching standard industry Applicant Tracking Systems. However, every company configures their ATS differently, so use our score as a strong baseline rather than a guarantee.' }
  ];

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      await axios.post('http://localhost:5001/api/contact', formData);
      toast.success('Message sent successfully! We will get back to you soon.');
      setFormData({ name: '', email: '', subject: '', message: '' });
    } catch (error) {
      toast.error('Failed to send message. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const contactInfo = [
    { icon: <Mail className="text-blue-400" />, title: 'Email Us', desc: 'support@ai-coach.com' },
    { icon: <Phone className="text-emerald-400" />, title: 'Call Us', desc: '+1 (555) 123-4567' },
    { icon: <MapPin className="text-violet-400" />, title: 'Location', desc: 'Silicon Valley, CA' },
  ];

  return (
    <div className="flex-grow p-8 max-w-6xl mx-auto w-full flex flex-col items-center">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-16 w-full">
        <h1 className="text-5xl font-bold mb-4">Get in <span className="text-gradient">Touch</span></h1>
        <p className="text-slate-400 text-lg max-w-2xl mx-auto">Have questions about the platform, want to report a bug, or just want to say hi? We'd love to hear from you.</p>
      </motion.div>

      <div className="w-full grid grid-cols-1 lg:grid-cols-3 gap-8 mb-20">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="lg:col-span-1 space-y-6">
          {contactInfo.map((info, i) => (
            <div key={i} className="glass p-6 rounded-2xl flex items-center gap-6 group hover:-translate-y-1 transition-transform border border-white/5 hover:border-blue-500/30">
              <div className="w-14 h-14 rounded-xl bg-white/5 flex items-center justify-center group-hover:scale-110 transition-transform">
                {info.icon}
              </div>
              <div>
                <h3 className="font-bold text-lg">{info.title}</h3>
                <p className="text-slate-400">{info.desc}</p>
              </div>
            </div>
          ))}

          <div className="glass p-8 rounded-2xl border border-white/5 bg-gradient-to-br from-blue-500/10 to-violet-500/10">
            <h3 className="font-bold text-xl mb-2 flex items-center gap-2"><MessageSquare className="text-blue-400"/> Support Hours</h3>
            <p className="text-slate-400 text-sm leading-relaxed mb-4">Our dedicated team is available to assist you during the following hours:</p>
            <div className="space-y-2 text-sm font-medium">
              <div className="flex justify-between"><span className="text-slate-400">Monday - Friday:</span> <span>9:00 AM - 6:00 PM EST</span></div>
              <div className="flex justify-between"><span className="text-slate-400">Saturday:</span> <span>10:00 AM - 2:00 PM EST</span></div>
              <div className="flex justify-between"><span className="text-slate-400">Sunday:</span> <span>Closed</span></div>
            </div>
          </div>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="lg:col-span-2">
          <form onSubmit={handleSubmit} className="glass p-8 rounded-3xl border border-white/5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-sm font-bold text-slate-400 mb-2">Your Name</label>
                <input required type="text" value={formData.name} onChange={(e) => setFormData({...formData, name: e.target.value})} className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all" placeholder="John Doe" />
              </div>
              <div>
                <label className="block text-sm font-bold text-slate-400 mb-2">Your Email</label>
                <input required type="email" value={formData.email} onChange={(e) => setFormData({...formData, email: e.target.value})} className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all" placeholder="john@example.com" />
              </div>
            </div>
            <div className="mb-6">
              <label className="block text-sm font-bold text-slate-400 mb-2">Subject</label>
              <input required type="text" value={formData.subject} onChange={(e) => setFormData({...formData, subject: e.target.value})} className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all" placeholder="How can we help you?" />
            </div>
            <div className="mb-8">
              <label className="block text-sm font-bold text-slate-400 mb-2">Message</label>
              <textarea required value={formData.message} onChange={(e) => setFormData({...formData, message: e.target.value})} className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all h-40 resize-none" placeholder="Write your message here..."></textarea>
            </div>
            <button disabled={isSubmitting} type="submit" className="w-full py-4 rounded-xl font-bold text-lg bg-gradient-to-r from-blue-500 to-violet-500 hover:shadow-lg hover:shadow-blue-500/25 transition-all flex justify-center items-center gap-2 text-white disabled:opacity-50">
              {isSubmitting ? <span className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></span> : <><Send size={20} /> Send Message</>}
            </button>
          </form>
        </motion.div>
      </div>

      <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="w-full max-w-3xl mx-auto">
        <h2 className="text-3xl font-bold mb-8 text-center">Frequently Asked <span className="text-gradient">Questions</span></h2>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="glass rounded-2xl border border-white/5 overflow-hidden">
              <button 
                onClick={() => setOpenFaqIndex(openFaqIndex === index ? null : index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
              >
                <span className="font-bold text-lg">{faq.question}</span>
                <ChevronDown className={`transition-transform duration-300 ${openFaqIndex === index ? 'rotate-180 text-blue-400' : 'text-slate-500'}`} />
              </button>
              <AnimatePresence>
                {openFaqIndex === index && (
                  <motion.div 
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="px-6 pb-5 text-slate-400 leading-relaxed"
                  >
                    {faq.answer}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default Contact;
